version: "3.9"

services:
  postgres:
    image: postgres:16
    container_name: dance-postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: dance_user
      POSTGRES_PASSWORD: dance_pass
      POSTGRES_DB: dance_comp
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata: